### ISSUE TITLE
The elispsis on firefox doesn't display correctly

### ISSUE THREAD

**Issue by Akeboshiwind** [kickscondor/fraidycat#108] opened 2020-03-13 16:18 UTC
On firefox the elipsis after a source is added is dislayed as a '⮨' character.

Here's a screenshot:
<img width="231" alt="Screenshot 2020-03-13 at 16 18 07" src="https://user-images.githubusercontent.com/8889986/76639565-405a5780-6546-11ea-94b3-b5d99b2ee020.png">

**Comment by benplumley** [comment] 2020-03-13 18:10
Seems to be a duplicate of https://github.com/kickscondor/fraidycat/issues/90.

**Comment by kickscondor** [comment] 2020-03-13 18:33
Yes, a duplicate - but thank you for caring enough to stop by!

**Closed by kickscondor** 2020-03-13 18:33 UTC

**Comment by Akeboshiwind** [comment] 2020-03-13 18:35
Ah I didn't look hard enough :/.

Enjoyed the app so far, thanks for putting it out there :)
