### ISSUE TITLE
"NetworkError when attempting to fetch resource." when trying to add Twitter profile

### ISSUE THREAD

**Issue by carlotrimarchi** [kickscondor/fraidycat#107] opened 2020-03-13 10:36 UTC
**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox
 - Version 73.0.1

**Describe the bug**
When trying to add a Twitter feed using their profile url (e.g. https://twitter.com/profile_name) I get the error "NetworkError when attempting to fetch resource."

**Comment by kickscondor** [comment] 2020-03-13 18:35
This is a duplicate of #26. In the Firefox settings, Tracking Protection needs to be set to **Standard**. I am looking for a fix, though. If you discover more issues, please report them on #26.

Thank you for reporting this nevertheless, Carlo!

**Closed by kickscondor** 2020-03-13 18:35 UTC
Labels: bug, duplicate
