### ISSUE TITLE
Ubuntu Firefox Nightly: Twitter Subscribe = NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by samim23** [kickscondor/fraidycat#83] opened 2020-03-03 16:22 UTC
**Desktop:**
 - OS: [Linux]
 - Browser [Firefox Nightly]
 - Version [75.0a1 (2020-02-28) (64-bit)]

**Describe the bug**
When trying to subscribe to a twitter feed in fraidycat, i get the following error popup: "NetworkError when attempting to fetch resource." It works when using Chrome or the debian app. Context: Firefox's "Enhanced Tracking Protection" and all adblockers (uBlock orign) are disabled for fraidycat.

ps. fraidycat is the most useful new thing i've seen online in many years. truly genius idea, thank you!

**Comment by kickscondor** [comment] 2020-03-03 23:27
I believe this is a duplicate of #45. Make sure Enhanced Tracking Protection is turned down to Standard. I can reproduce this when it is at 'Strict'. Otherwise it has been fine for me.

But perhaps there is another extension in conflict. It can be tricky! Thank you for chiming in.

**Comment by kickscondor** [comment] 2020-04-09 00:02
Is this still an issue in the most recent Firefox?

**Closed** 2020-06-20 05:27 UTC
Labels: bug
